//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Recipe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int RecipeId { get; set; }
        public int StepOrderNumber { get; set; }
        public string ImageSource { get; set; }
    
        public virtual Step Step { get; set; }
    }
}
