//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Recipe.Model
{
    using Food_Recipe.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient : BaseViewModel
    {
        private int _recipeId;
        public int RecipeId { get => _recipeId; set { _recipeId = value; OnPropertyChanged(); } }

        private string _name;
        public string Name { get => _name; set { _name = value; OnPropertyChanged(); } }

        private string _quantity;
        public string Quantity { get => _quantity; set { _quantity = value; OnPropertyChanged(); } }

        public virtual Recipe Recipe { get; set; }
    }
}
