//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Recipe.Model
{
    using Food_Recipe.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.Steps = new HashSet<Step>();
        }

        private int _id;
        public int Id { get => _id; set { _id = value; OnPropertyChanged(); } }

        private string _name;
        public string Name { get => _name; set { _name = value; OnPropertyChanged(); } }

        private string _youtubeSource;
        public string YoutubeSource { get => _youtubeSource; set { _youtubeSource = value; OnPropertyChanged(); } }

        private Nullable<int> _isFavorite;
        public Nullable<int> IsFavorite { get => _isFavorite; set { _isFavorite = value; OnPropertyChanged(); } }

        private string _avatarSource;
        public string AvatarSource { get => _avatarSource; set { _avatarSource = value; OnPropertyChanged(); } }

        private Nullable<int> _category;
        public Nullable<int> Category { get => _category; set { _category = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _createdTime;
        public Nullable<System.DateTime> CreatedTime { get => _createdTime; set { _createdTime = value; OnPropertyChanged(); } }

        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Step> Steps { get; set; }
    }
}
